<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Proxion.Windows</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Proxion.Core/Proxion.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/proxion.ico" LogicalName="Proxion.Windows.Assets.proxion.ico" />
    <EmbeddedResource Include="Assets/ProxyBridge/ProxyBridge_CLI.exe" LogicalName="Proxion.Windows.Assets.ProxyBridge.ProxyBridge_CLI.exe" />
    <EmbeddedResource Include="Assets/ProxyBridge/ProxyBridgeCore.dll" LogicalName="Proxion.Windows.Assets.ProxyBridge.ProxyBridgeCore.dll" />
    <EmbeddedResource Include="Assets/ProxyBridge/WinDivert.dll" LogicalName="Proxion.Windows.Assets.ProxyBridge.WinDivert.dll" />
    <EmbeddedResource Include="Assets/ProxyBridge/WinDivert64.sys" LogicalName="Proxion.Windows.Assets.ProxyBridge.WinDivert64.sys" />
  </ItemGroup>

</Project>
